Make it clear that documentation is out dated
Enalean/tuleap-documentation-fr pull request #75
Opened 2022-05-16 15:48 UTC by vaceletm

Take the opportunity to remove old/outdated pieces.

2022-05-16 16:15 UTC, nterray requested changes

2022-05-16 16:15 UTC, nterray commented on languages/fr/user-guide/cvs.rst
> +.. attention::
Could you please put it above the toc like for index?

2022-05-16 16:15 UTC, nterray commented on languages/fr/user-guide/git.rst
> +.. attention::
Could you please put it above the toc like for index?

2022-05-16 16:15 UTC, nterray commented on languages/fr/user-guide/doc.rst
> +.. attention::
Could you please put it above the toc like for index?`

2022-05-17 06:59 UTC, vaceletm commented on languages/fr/index.rst
> +   Il est recommandé de se réfèrer à la version `anglaise </doc/en/>`_.
It's the default configuration shipped with Tuleap nginx configuration. I doubt someone changed that.

2022-05-18 07:21 UTC, LeSuisse approved these changes

2022-05-18 07:21 UTC, merged